### ISSUE TITLE
How do I style a blockquote?

### ISSUE THREAD

**Issue by kama003** [cnvs/canvas#671]
![Screenshot (1)](https://user-images.githubusercontent.com/45000219/77169347-571d2300-6adf-11ea-9459-d0487c4e37d8.png)
![Screenshot (2)](https://user-images.githubusercontent.com/45000219/77169412-73b95b00-6adf-11ea-9851-e6cac4942ac2.png)
![Screenshot (3)](https://user-images.githubusercontent.com/45000219/77169447-8338a400-6adf-11ea-818b-1fa8ab6f2ccc.png)

**Comment by austintoddj** [comment]
Since Canvas simply renders the data as HTML, there isn't any styling that will carry over to the frontend. This allows developers to display the content however they like.

Target the blockquote on the page with some CSS:
```css
.blog-content blockquote {
    margin-top: 2em;
    font-style: italic;
    font-size: 28px;
    color: #ccc;
    padding-left: 1.5em;
    line-height: 1.5;
}
```
